language: java
sudo: true
dist: trusty

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories:
    - "$HOME/.m2"

before_cache:
  - rm -rf $HOME/.m2/repository/com/unq/dapp/2020/c1/comprando-en-casa

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r target/jacoco/jacoco.xml

jdk:
  - oraclejdk8